# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.3
  codecov: codecov/codecov@1.2.0

ref:
  container: &container
    docker:
      - image: node:12.22.0
    working_directory: ~/repo

commands:
  install-packages:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          cache-path: |
            ~/.yarn
            node_modules

jobs:
  lint:
    <<: *container
    steps:
      - checkout
      - install-packages
      - run:
          name: Lint
          command: yarn lint

  build:
    <<: *container
    steps:
      - checkout
      - install-packages
      - run:
          name: Build
          command: yarn build

  test:
    <<: *container
    steps:
      - checkout
      - install-packages
      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: 'coverage/clover.xml'
          flags: integration

workflows:
  build-and-test:
    jobs:
      - lint
      - build
      - test
